materials = [
	"Amber",
	"Ancient Mask",
	"Beast Hide",
	"Black Pearl",
	"Boar Meat",
	"Broken Battery",
	"Broken Circuit",
	"Broken Key",
	"Copper Ore",
	"Clean Nut",
	"Complex Gadget",
	"Crushed Nut",
	"Crystal",
	"Drab Bracelet",
	"Dented Plate",
	"Dented Socket",
	"Dye",
	"Eagle Eggs",
	"Elaborate Gadget",
	"Filler Metal",
	"Giant Egg",
	"Gold Ore",
	"Iron Ore",
	"Large Battery",
	"Large Gear",
	"Lovely Choker",
	"Machine Arm",
	"Machine Core",
	"Machine Head",
	"Machine Leg",
	"Machine Oil",
	"Machine Torso",
	"Memory Alloy",
	"Meteorite",
	"Meteorite Shard",
	"Moldavite",
	"Moose Meat",
	"Mushroom",
	"Natural Rubber",
	"New Bolt",
	"Pearl",
	"Plant Seed",
	"Popola's Booze",
	"Powerup Part L",
	"Powerup Part M",
	"Powerup Part S",
	"Precious Earrings",
	"Pristine Cable",
	"Pristine Screw",
	"Pure Water",
	"Pyrite",
	"Rusted Clump",
	"Rusty Bolt",
	"Severed Cable",
	"Shattered Earrings",
	"Silver Ore",
	"Simple Gadget",
	"Small Gear",
	"Stretched Coil",
	"Stripped Screw",
	"Sturdy Socket",
	"Tanning Agent",
	"Tech Manual",
	"Thick Dictionary",
	"Titanium Alloy",
	"Torn Book",
	"Tree Sap",
	"Tree Seed",
	"Viscous Oil",
	"Warped Wire",
]

for material in materials:
	print("  " + material + ":")
	print("    recipes:")
	print("    - output: 1")
	print("      recipe_type: Raw Resource")
	print("      requirements:")
	print("        "+material+": 0")
	print("")